version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: product_postgres
    restart: always
    environment:
      POSTGRES_USER: imshadwal
      POSTGRES_PASSWORD: hello00786
      POSTGRES_DB: productdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U imshadwal"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: ./product-management-backend
    container_name: product_backend
    restart: always
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://imshadwal:hello00786@postgres:5432/productdb?schema=public
    depends_on:
      postgres:
        condition: service_healthy

  frontend:
    build: ./product-management-frontend
    container_name: product_frontend
    restart: always
    ports:
      - "5173:80"
    depends_on:
      - backend

volumes:
  pgdata:
